name: source_gen_help
description: Some helpers for source_gen
version: 0.0.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  source_gen: "^0.5.1"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
